import { getSession } from "next-auth/react";
import Head from "next/head";
import Feed from "../components/Feed";
import Header from "../components/Header";
import Login from "../components/Login";
import RightSideBar from "../components/RightSideBar";
import Sidebar from "../components/Sidebar";

export default function Home({session}) {
  if(!session)
    return <Login/>
  return (
    <div>
      <Head>
        <title>Facebook clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://upload.wikimedia.org/wikipedia/en/thumb/0/04/Facebook_f_logo_%282021%29.svg/800px-Facebook_f_logo_%282021%29.svg.png" />
      </Head>

      <Header/>

      <main className="flex bg-gray-100">
        {/* left sidebar */}
        <Sidebar/>
        {/* feed (create & read posts) */}
        <Feed/>
        {/* right sidebar */}
        <RightSideBar/>
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);
  return{
    props: {session},
  }
}
